export const FETCH_BEERS_REQUEST = 'timeline:FETCH_BEERS_REQUEST';
export const FETCH_BEERS_SUCCESS = 'timeline:FETCH_BEERS_SUCCESS';
export const FETCH_BEERS_FAILURE = 'timeline:FETCH_BEERS_FAILURE';
